# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmE5NzQ0NmYwY2Q4ODBmNDA5NTY5OTcwZjY1NjEwNmQxMTk3NTM4MzgxZjE2NTkzYTgzOTgxMGJlNDIwYzczZGU5MWIzMjUzNzY5ZmFhYjA2YjI5YTkyYjc1YjMzNTcxNjZjYjRhMWFlMmJkZWRjOWY3YzllM2NlNzI0MWYyOTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
